# Generated by Django 3.2.9 on 2021-11-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupation', '0002_alter_occupation_fire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='fraction',
            field=models.IntegerField(verbose_name='Fraction(%)'),
        ),
    ]
