version: '3.8'
   
services:
   backend:
    build: backend
    command: sh ./run.sh
    volumes:
      - ./backend:/srv/project
    ports:
      - "8081:8081"
   frontend:
    build: frontend
    container_name: frontend
    restart: always
    command: sh ./run.sh
    depends_on:
     - backend
    ports:
     - "8080:8080"
        
